[project]
authors = ["ecamo19 <erickcamo19@gmail.com>", "Choat lab"]
channels = ["conda-forge"]
description = "Code for getting weight measurements from Phidget's load cells"
name = "choatlab_lysimeters"
platforms = ["linux-64", "osx-64", "linux-aarch64"]
version = "0.3.45"

[dependencies]
bash_kernel = ">=0.7.2,<0.10"
pip = ">=24.3.1,<25"
python = "==3.10.0"
bash = ">=5.2.37,<6"
time = ">=1.9,<2"
ruff = ">=0.12.3,<0.13"
tmux = ">=3.5,<4"
pathlib = ">=1.0.1,<2"
emoji = ">=2.14.1,<3"
p7zip = ">=16.2,<17"
rclone = ">=1.70.3,<2"

[pypi-dependencies]
phidget22 = "*"  

[host-dependencies]
python = "==3.10.0"

[tasks]
balance = { cmd = "python main_balance.py", cwd = "src"}
