# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/lysimeters_code',
                'doc_host': 'https://ecamo19.github.io',
                'git_url': 'https://github.com/ecamo19/lysimeters_code',
                'lib_path': 'lysimeters_code'},
  'syms': {'lysimeters_code.core': {'lysimeters_code.core.foo': ('core.html#foo', 'lysimeters_code/core.py')}}}
